# Generated by Django 5.2.1 on 2025-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='SKU')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(blank=True, max_length=50, verbose_name='Categoria')),
                ('tamanho', models.CharField(blank=True, max_length=10, verbose_name='Tamanho')),
                ('cor', models.CharField(blank=True, max_length=30, verbose_name='Cor')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em estoque')),
            ],
        ),
    ]
