# Generated by Django 5.2.1 on 2025-05-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
