# Generated by Django 5.2.1 on 2025-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_produto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
