# Generated by Django 5.2.1 on 2025-05-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_categoria_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Custo (R$)'),
        ),
    ]
