# Generated by Django 5.2.1 on 2025-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descricao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
    ]
